# Generated by Django 5.1.3 on 2024-11-05 20:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('is_active', models.BooleanField(default=True)),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('implied_volatility', models.FloatField()),
                ('historical_volatility', models.FloatField()),
                ('skew', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'created_at'], name='signals_mar_ticker_012b70_idx')],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('is_active', models.BooleanField(default=True)),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('strategy', models.CharField(choices=[('VRP', 'Volatility Risk Premium'), ('SKEW', 'Volatility Skew'), ('TERM', 'Term Structure')], max_length=10)),
                ('vrp_zscore', models.FloatField()),
                ('vrp_ratio', models.FloatField()),
                ('expected_return', models.FloatField()),
                ('confidence', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('in_lab', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'strategy', 'created_at'], name='signals_sig_ticker_a52fdf_idx'), models.Index(fields=['is_active', 'expires_at'], name='signals_sig_is_acti_9fa819_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('taken', 'Taken'), ('watching', 'Watching'), ('passed', 'Passed')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('position_size', models.IntegerField(null=True)),
                ('pnl', models.FloatField(null=True)),
                ('exit_price', models.FloatField(null=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.signal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'signal', 'status'], name='signals_use_user_id_2ac735_idx'), models.Index(fields=['created_at'], name='signals_use_created_bd653e_idx')],
                'unique_together': {('user',)},
            },
        ),
    ]
