# Generated by Django 5.1.3 on 2024-11-05 21:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='marketdata',
            name='signals_mar_ticker_012b70_idx',
        ),
        migrations.RemoveIndex(
            model_name='signal',
            name='signals_sig_ticker_a52fdf_idx',
        ),
        migrations.RemoveIndex(
            model_name='signal',
            name='signals_sig_is_acti_9fa819_idx',
        ),
        migrations.RemoveIndex(
            model_name='userinteraction',
            name='signals_use_user_id_2ac735_idx',
        ),
        migrations.RemoveIndex(
            model_name='userinteraction',
            name='signals_use_created_bd653e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userinteraction',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='signal',
            name='confidence',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinteractions', to='signals.signal'),
        ),
    ]
