# Generated by Django 5.1.3 on 2024-11-05 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_remove_marketdata_signals_mar_ticker_012b70_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinteraction',
            unique_together={('user', 'signal')},
        ),
        migrations.AddIndex(
            model_name='marketdata',
            index=models.Index(fields=['ticker', 'created_at'], name='signals_mar_ticker_012b70_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['ticker', 'strategy', 'created_at'], name='signals_sig_ticker_a52fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['is_active', 'expires_at'], name='signals_sig_is_acti_9fa819_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['signal', 'status'], name='signals_use_signal__b13624_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['created_at'], name='signals_use_created_bd653e_idx'),
        ),
    ]
